services:
  - type: web
    name: identity-reconciliation
    env: node
    plan: free
    buildCommand: npm install && npm install typescript --save-dev && npx prisma generate && npx tsc
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString

databases:
  - name: bitespeed-db
    plan: free    